<a href="https://colab.research.google.com/github/Sunnn-y/NaturalLanguageProcessing/blob/main/20231016_%EB%8B%A8%EC%96%B4%EC%9D%98_%ED%91%9C%ED%98%84_%EC%8B%A4%EC%8A%B5(BoW%2C_TF_IDF).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# BOW 직접 구현

## 실습 2(단어의 순서를 고려하지 않은 BOW)

In [ ]:
docs = ['나는 양념 치킨을 좋아해 하지만 후라이드 치킨을 싫어해',
        '나는 후라이드 치킨을 좋아해 하지만 양념 치킨을 싫어해']

In [ ]:
docs_ls = []

for doc in docs:
  docs_ls.append(doc.split(' '))

docs_ls

[['나는', '양념', '치킨을', '좋아해', '하지만', '후라이드', '치킨을', '싫어해'],
 ['나는', '후라이드', '치킨을', '좋아해', '하지만', '양념', '치킨을', '싫어해']]

In [ ]:
from collections import defaultdict

word2id = defaultdict(lambda : len(word2id))

for doc in docs_ls:
  for token in doc:
    word2id[token]

word2id

defaultdict(<function __main__.<lambda>()>,
            {'나는': 0,
             '양념': 1,
             '치킨을': 2,
             '좋아해': 3,
             '하지만': 4,
             '후라이드': 5,
             '싫어해': 6})

In [ ]:
import numpy as np
BoW_ls = []
for i, doc in enumerate(docs_ls):
  bow = np.zeros(len(word2id), dtype = int)
  for token in doc:
    bow[word2id[token]] += 1
  BoW_ls.append(bow.tolist())

In [ ]:
BoW_ls

[[1, 1, 2, 1, 1, 1, 1], [1, 1, 2, 1, 1, 1, 1]]

In [ ]:
from IPython.core import display as ICD
import pandas as pd
sorted_vocab = sorted((value, key) for key, value in word2id.items())
print('sorted_vocab', sorted_vocab)

vocab = []
for v in sorted_vocab:
  vocab.append(v[1])
print('vocab', vocab)

for i in range(len(docs)):
  print("문서{} : {}".format(i,docs[i]))
  ICD.display(pd.DataFrame([BoW_ls[i]], columns=vocab))
  print("\n\n")

sorted_vocab [(0, '나는'), (1, '양념'), (2, '치킨을'), (3, '좋아해'), (4, '하지만'), (5, '후라이드'), (6, '싫어해')]
vocab ['나는', '양념', '치킨을', '좋아해', '하지만', '후라이드', '싫어해']
문서0 : 나는 양념 치킨을 좋아해 하지만 후라이드 치킨을 싫어해


나는  양념  치킨을  좋아해  하지만  후라이드  싫어해
0   1   1    2    1    1     1    1




문서1 : 나는 후라이드 치킨을 좋아해 하지만 양념 치킨을 싫어해


나는  양념  치킨을  좋아해  하지만  후라이드  싫어해
0   1   1    2    1    1     1    1

# TF-IDF 직접 구현

## 실습

In [ ]:
docs = ['오늘 동물원에서 원숭이와 코끼리를 봤어',
        '동물원에서 원숭이에게 바나나를 줬어 바나나를']

1. 토큰화 : 공백으로 토큰화 진행

In [ ]:
docs_ls = []

for doc in docs:
  docs_ls.append(doc.split(' '))

docs_ls

[['오늘', '동물원에서', '원숭이와', '코끼리를', '봤어'],
 ['동물원에서', '원숭이에게', '바나나를', '줬어', '바나나를']]

2. 유니크한 토큰 사전 구하기

In [ ]:
from collections import defaultdict

word2id = defaultdict(lambda : len(word2id))

for doc in docs_ls:
  for token in doc:
    word2id[token]

dict1 = []
for idx, val in enumerate(word2id):
  dict1.append(val)

word2id

defaultdict(<function __main__.<lambda>()>,
            {'오늘': 0,
             '동물원에서': 1,
             '원숭이와': 2,
             '코끼리를': 3,
             '봤어': 4,
             '원숭이에게': 5,
             '바나나를': 6,
             '줬어': 7})

3. TF 계산하기

In [ ]:
import numpy as np

TF_ls1 = [] # 문서 내 토큰 빈도
TF_ls2 = [] # 문서 내 전체 토큰 빈도
for i, doc in enumerate(docs_ls):
  TF1 = np.zeros(len(word2id), dtype = int)
  TF2 = []
  for token in doc:
    TF1[word2id[token]] += 1
  for freq in range(len(word2id)):
    TF2.append(len(docs_ls[i]))
  TF_ls1.append(TF1.tolist())
  TF_ls2.append(TF2)

In [ ]:
TF_ls1

[[1, 1, 1, 1, 1, 0, 0, 0], [0, 1, 0, 0, 0, 1, 2, 1]]

In [ ]:
TF_ls2

[[5, 5, 5, 5, 5, 5, 5, 5], [5, 5, 5, 5, 5, 5, 5, 5]]

In [ ]:
# 문서 1의 TF
TF1 = []
for m in range(len(TF_ls1[0])):
  TF1.append(TF_ls1[0][m] / TF_ls2[0][m])

import pandas as pd
docu1 = pd.DataFrame({'문서내 토큰 빈도' : TF_ls1[0],
                      '문서내 전체 토큰 빈도' : TF_ls2[0],
                      'TF' : TF1},
                      index = dict1
                    )
docu1

문서내 토큰 빈도  문서내 전체 토큰 빈도   TF
오늘             1             5  0.2
동물원에서          1             5  0.2
원숭이와           1             5  0.2
코끼리를           1             5  0.2
봤어             1             5  0.2
원숭이에게          0             5  0.0
바나나를           0             5  0.0
줬어             0             5  0.0

In [ ]:
# 문서 2의 TF
TF2 = []
for m in range(len(TF_ls1[1])):
  TF2.append(TF_ls1[1][m] / TF_ls2[1][m])

docu2 = pd.DataFrame({'문서내 토큰 빈도' : TF_ls1[1],
                      '문서내 전체 토큰 빈도' : TF_ls2[1],
                      'TF' : TF2},
                       index = dict1
                    )
docu2

문서내 토큰 빈도  문서내 전체 토큰 빈도   TF
오늘             0             5  0.0
동물원에서          1             5  0.2
원숭이와           0             5  0.0
코끼리를           0             5  0.0
봤어             0             5  0.0
원숭이에게          1             5  0.2
바나나를           2             5  0.4
줬어             1             5  0.2

4. IDF 계산하기

In [ ]:
IDF_ls1 = [] # 문서 수
IDF_ls2 = np.zeros(len(word2id), dtype = int) # 문서가 등장한 토큰 수
for doc in word2id:
  IDF_ls1.append(len(docs))

for idx, val in enumerate(word2id):
  for t in dict1:
    if val in docs_ls[0]:
      IDF_ls2[idx] += 1
      break

for idx, val in enumerate(word2id):
  for t in dict1:
    if val in docs_ls[1]:
      IDF_ls2[idx] += 1
      break

In [ ]:
IDF_ls1

[2, 2, 2, 2, 2, 2, 2, 2]

In [ ]:
IDF_ls2

array([1, 2, 1, 1, 1, 1, 1, 1])

In [ ]:
import math
IDF = []
for m in range(len(IDF_ls1)):
  IDF.append(math.log10(IDF_ls1[m]/IDF_ls2[m]))

docu3 = pd.DataFrame({'문서수' : IDF_ls1,
                      '문서가 등장한 토큰 수' : IDF_ls2,
                      'IDF' : IDF},
                     index = dict1
                 )
docu3

문서수  문서가 등장한 토큰 수      IDF
오늘       2             1  0.30103
동물원에서    2             2  0.00000
원숭이와     2             1  0.30103
코끼리를     2             1  0.30103
봤어       2             1  0.30103
원숭이에게    2             1  0.30103
바나나를     2             1  0.30103
줬어       2             1  0.30103

5. TF-IDF 계산하기

In [ ]:
# 문서 1의 TF-IDF
TFIDF1 = []
for m in range(len(TF1)):
  TFIDF1.append(TF1[m] * IDF[m])

TFIDFdocu1 = pd.DataFrame({'TF' : TF1,
                      'IDF' : IDF,
                       'TF-IDF' : TFIDF1},
                     index = dict1
                 )
TFIDFdocu1

TF      IDF    TF-IDF
오늘     0.2  0.30103  0.060206
동물원에서  0.2  0.00000  0.000000
원숭이와   0.2  0.30103  0.060206
코끼리를   0.2  0.30103  0.060206
봤어     0.2  0.30103  0.060206
원숭이에게  0.0  0.30103  0.000000
바나나를   0.0  0.30103  0.000000
줬어     0.0  0.30103  0.000000

In [ ]:
# 문서 2의 TF-IDF
TFIDF2 = []
for m in range(len(TF2)):
  TFIDF2.append(TF2[m] * IDF[m])

TFIDFdocu2 = pd.DataFrame({'TF' : TF2,
                          'IDF' : IDF,
                          'TF-IDF' : TFIDF2},
                     index = dict1
                 )
TFIDFdocu2

TF      IDF    TF-IDF
오늘     0.0  0.30103  0.000000
동물원에서  0.2  0.00000  0.000000
원숭이와   0.0  0.30103  0.000000
코끼리를   0.0  0.30103  0.000000
봤어     0.0  0.30103  0.000000
원숭이에게  0.2  0.30103  0.060206
바나나를   0.4  0.30103  0.120412
줬어     0.2  0.30103  0.060206

## 다른 방식으로 풀이

In [1]:
docs = ['오늘 동물원에서 원숭이와 코끼리를 봤어',
        '동물원에서 원숭이에게 바나나를 줬어 바나나를']

1. 토큰화 : 공백으로 토큰화 진행

In [2]:
doc_ls = []

for doc in docs:
  doc_ls.append(doc.split(' '))

doc_ls

[['오늘', '동물원에서', '원숭이와', '코끼리를', '봤어'],
 ['동물원에서', '원숭이에게', '바나나를', '줬어', '바나나를']]

2. 유니크한 토큰 사전 구하기<br/>
  2-1. 빈 딕셔너리 생성

In [3]:
from collections import defaultdict

word2id = defaultdict(lambda : len(word2id))
word2id

defaultdict(<function __main__.<lambda>()>, {})

2-2. 위에서 생성한 빈 딕셔너리에 유니크한 토큰 넣기

In [4]:
for doc in doc_ls:
  for token in doc:
    word2id[token]
    print(token)
    print('\t',word2id)
word2id

오늘
	 defaultdict(<function <lambda> at 0x78b224be8700>, {'오늘': 0})
동물원에서
	 defaultdict(<function <lambda> at 0x78b224be8700>, {'오늘': 0, '동물원에서': 1})
원숭이와
	 defaultdict(<function <lambda> at 0x78b224be8700>, {'오늘': 0, '동물원에서': 1, '원숭이와': 2})
코끼리를
	 defaultdict(<function <lambda> at 0x78b224be8700>, {'오늘': 0, '동물원에서': 1, '원숭이와': 2, '코끼리를': 3})
봤어
	 defaultdict(<function <lambda> at 0x78b224be8700>, {'오늘': 0, '동물원에서': 1, '원숭이와': 2, '코끼리를': 3, '봤어': 4})
동물원에서
	 defaultdict(<function <lambda> at 0x78b224be8700>, {'오늘': 0, '동물원에서': 1, '원숭이와': 2, '코끼리를': 3, '봤어': 4})
원숭이에게
	 defaultdict(<function <lambda> at 0x78b224be8700>, {'오늘': 0, '동물원에서': 1, '원숭이와': 2, '코끼리를': 3, '봤어': 4, '원숭이에게': 5})
바나나를
	 defaultdict(<function <lambda> at 0x78b224be8700>, {'오늘': 0, '동물원에서': 1, '원숭이와': 2, '코끼리를': 3, '봤어': 4, '원숭이에게': 5, '바나나를': 6})
줬어
	 defaultdict(<function <lambda> at 0x78b224be8700>, {'오늘': 0, '동물원에서': 1, '원숭이와': 2, '코끼리를': 3, '봤어': 4, '원숭이에게': 5, '바나나를': 6, '줬어': 7})
바나나를
	 defaultdict(<function <l

defaultdict(<function __main__.<lambda>()>,
            {'오늘': 0,
             '동물원에서': 1,
             '원숭이와': 2,
             '코끼리를': 3,
             '봤어': 4,
             '원숭이에게': 5,
             '바나나를': 6,
             '줬어': 7})

3. TF 계산하기<br/>
TF = (특정 단어 등장빈도) / (문서내 전체 등장 단어빈도)

In [5]:
import numpy as np

TDM = np.zeros((len(word2id), len(doc_ls)), dtype=int)

for i, doc in enumerate(doc_ls):
  print(doc)
  for token in doc:
    TDM[word2id[token], i] += 1 # 해당 토큰의 위치(column)
    print(token)
    print(TDM)
    print('\t')

['오늘', '동물원에서', '원숭이와', '코끼리를', '봤어']
오늘
[[1 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]]
	
동물원에서
[[1 0]
 [1 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]]
	
원숭이와
[[1 0]
 [1 0]
 [1 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]]
	
코끼리를
[[1 0]
 [1 0]
 [1 0]
 [1 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]]
	
봤어
[[1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [0 0]
 [0 0]
 [0 0]]
	
['동물원에서', '원숭이에게', '바나나를', '줬어', '바나나를']
동물원에서
[[1 0]
 [1 1]
 [1 0]
 [1 0]
 [1 0]
 [0 0]
 [0 0]
 [0 0]]
	
원숭이에게
[[1 0]
 [1 1]
 [1 0]
 [1 0]
 [1 0]
 [0 1]
 [0 0]
 [0 0]]
	
바나나를
[[1 0]
 [1 1]
 [1 0]
 [1 0]
 [1 0]
 [0 1]
 [0 1]
 [0 0]]
	
줬어
[[1 0]
 [1 1]
 [1 0]
 [1 0]
 [1 0]
 [0 1]
 [0 1]
 [0 1]]
	
바나나를
[[1 0]
 [1 1]
 [1 0]
 [1 0]
 [1 0]
 [0 1]
 [0 2]
 [0 1]]
	


In [6]:
# TF = (특정 단어 등장빈도) / (문서내 전체 등장 단어빈도)
def computeTF(TDM):
  doc_len = len(docs) # 문서 개수 2개
  word_len = len(word2id)
  print('문서수 : ',doc_len)
  print('전체 단어수 : ', word_len)

  tf = np.zeros((word_len,doc_len))
  print(tf)

  for doc_i in range(len(doc_ls)):
    print(docs[doc_i])
    for word_i in range(len(word2id)):
      tf[word_i,doc_i] = TDM[word_i,doc_i]/TDM[:,doc_i].sum()
    print(tf)
  return tf

In [7]:
tf = computeTF(TDM)

문서수 :  2
전체 단어수 :  8
[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]
오늘 동물원에서 원숭이와 코끼리를 봤어
[[0.2 0. ]
 [0.2 0. ]
 [0.2 0. ]
 [0.2 0. ]
 [0.2 0. ]
 [0.  0. ]
 [0.  0. ]
 [0.  0. ]]
동물원에서 원숭이에게 바나나를 줬어 바나나를
[[0.2 0. ]
 [0.2 0.2]
 [0.2 0. ]
 [0.2 0. ]
 [0.2 0. ]
 [0.  0.2]
 [0.  0.4]
 [0.  0.2]]


In [8]:
tf

array([[0.2, 0. ],
       [0.2, 0.2],
       [0.2, 0. ],
       [0.2, 0. ],
       [0.2, 0. ],
       [0. , 0.2],
       [0. , 0.4],
       [0. , 0.2]])

4. IDF 계산하기<br/>
IDF = -log(단어가 등장한 문서 수 / 총 문서수)

In [9]:
import math
# IDF = -log(단어가 등장한 문서 수 / 총 문서수)
def computeIDF(TDM):
  doc_len = len(docs) # 문서개수 2개
  word_len = len(word2id)
  print('문서수 : ',doc_len)
  print('전체 단어수 : ', word_len)

  idf = np.zeros(word_len)
  print(idf)

  for doc_i in range(len(doc_ls)):
    for word_i in range(len(word2id)):
      idf[word_i] = -math.log10(np.count_nonzero(TDM[word_i,:]) / doc_len)
  print(idf)
  return idf

In [10]:
idf = computeIDF(TDM)
idf

문서수 :  2
전체 단어수 :  8
[0. 0. 0. 0. 0. 0. 0. 0.]
[ 0.30103 -0.       0.30103  0.30103  0.30103  0.30103  0.30103  0.30103]


array([ 0.30103, -0.     ,  0.30103,  0.30103,  0.30103,  0.30103,
        0.30103,  0.30103])

5. TF-IDF 계산하기

In [11]:
# TF-IDF 곱
def computeTFIDF(TDM):
  tf = computeTF(TDM)
  idf = computeIDF(TDM)
  tfidf = np.zeros(tf.shape)

  for doc_i in range(len(doc_ls)):
    print(docs[doc_i])
    for word_i in range(len(word2id)):
      tfidf[word_i, doc_i] = tf[word_i, doc_i] * idf[word_i]

  print('TF-IDF 최종')
  print(tfidf)
  return tfidf

In [12]:
tfidf = computeTFIDF(TDM)

문서수 :  2
전체 단어수 :  8
[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]
오늘 동물원에서 원숭이와 코끼리를 봤어
[[0.2 0. ]
 [0.2 0. ]
 [0.2 0. ]
 [0.2 0. ]
 [0.2 0. ]
 [0.  0. ]
 [0.  0. ]
 [0.  0. ]]
동물원에서 원숭이에게 바나나를 줬어 바나나를
[[0.2 0. ]
 [0.2 0.2]
 [0.2 0. ]
 [0.2 0. ]
 [0.2 0. ]
 [0.  0.2]
 [0.  0.4]
 [0.  0.2]]
문서수 :  2
전체 단어수 :  8
[0. 0. 0. 0. 0. 0. 0. 0.]
[ 0.30103 -0.       0.30103  0.30103  0.30103  0.30103  0.30103  0.30103]
오늘 동물원에서 원숭이와 코끼리를 봤어
동물원에서 원숭이에게 바나나를 줬어 바나나를
TF-IDF 최종
[[ 0.060206  0.      ]
 [-0.       -0.      ]
 [ 0.060206  0.      ]
 [ 0.060206  0.      ]
 [ 0.060206  0.      ]
 [ 0.        0.060206]
 [ 0.        0.120412]
 [ 0.        0.060206]]


In [13]:
tfidf

array([[ 0.060206,  0.      ],
       [-0.      , -0.      ],
       [ 0.060206,  0.      ],
       [ 0.060206,  0.      ],
       [ 0.060206,  0.      ],
       [ 0.      ,  0.060206],
       [ 0.      ,  0.120412],
       [ 0.      ,  0.060206]])

6. 시각화로 확인

In [14]:
import pandas as pd

sorted_vocab = sorted((value, key) for key, value in word2id.items())
vocab = [v[1] for v in sorted_vocab]
print('vocab : ', vocab)
tfidf = computeTFIDF(TDM)
pd.DataFrame(tfidf.T, columns = vocab)

vocab :  ['오늘', '동물원에서', '원숭이와', '코끼리를', '봤어', '원숭이에게', '바나나를', '줬어']
문서수 :  2
전체 단어수 :  8
[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]
오늘 동물원에서 원숭이와 코끼리를 봤어
[[0.2 0. ]
 [0.2 0. ]
 [0.2 0. ]
 [0.2 0. ]
 [0.2 0. ]
 [0.  0. ]
 [0.  0. ]
 [0.  0. ]]
동물원에서 원숭이에게 바나나를 줬어 바나나를
[[0.2 0. ]
 [0.2 0.2]
 [0.2 0. ]
 [0.2 0. ]
 [0.2 0. ]
 [0.  0.2]
 [0.  0.4]
 [0.  0.2]]
문서수 :  2
전체 단어수 :  8
[0. 0. 0. 0. 0. 0. 0. 0.]
[ 0.30103 -0.       0.30103  0.30103  0.30103  0.30103  0.30103  0.30103]
오늘 동물원에서 원숭이와 코끼리를 봤어
동물원에서 원숭이에게 바나나를 줬어 바나나를
TF-IDF 최종
[[ 0.060206  0.      ]
 [-0.       -0.      ]
 [ 0.060206  0.      ]
 [ 0.060206  0.      ]
 [ 0.060206  0.      ]
 [ 0.        0.060206]
 [ 0.        0.120412]
 [ 0.        0.060206]]


오늘  동물원에서      원숭이와      코끼리를        봤어     원숭이에게      바나나를        줬어
0  0.060206   -0.0  0.060206  0.060206  0.060206  0.000000  0.000000  0.000000
1  0.000000   -0.0  0.000000  0.000000  0.000000  0.060206  0.120412  0.060206

## sklearn 으로 풀이

In [15]:
docs = ['오늘 동물원에서 원숭이와 코끼리를 봤어',
        '동물원에서 원숭이에게 바나나를 줬어 바나나를']

from sklearn.feature_extraction.text import TfidfVectorizer
tfidv = TfidfVectorizer()
tfidv = tfidv.fit(docs)
tfidv.transform(docs).toarray()
vocab = tfidv.get_feature_names_out()

In [16]:
import pandas as pd
df = pd.DataFrame(tfidv.transform(docs).toarray(), columns = vocab)
df

동물원에서      바나나를        봤어        오늘     원숭이에게      원숭이와        줬어  \
0  0.335176  0.000000  0.471078  0.471078  0.000000  0.471078  0.000000   
1  0.278943  0.784088  0.000000  0.000000  0.392044  0.000000  0.392044   

       코끼리를  
0  0.471078  
1  0.000000